Repository fosslight/fosslight_scanner, pull requests merged in 2022-02, with the labels that each got.

#14 Add a FOSSLight Binary
  requirements.txt
  src/fosslight_scanner/_get_input.py
  src/fosslight_scanner/_help.py
  src/fosslight_scanner/fosslight_scanner.py
Labels: enhancement

#16 Add a FOSSLight Reuse
  requirements.txt
  src/fosslight_scanner/_get_input.py
  src/fosslight_scanner/common.py
  src/fosslight_scanner/fosslight_scanner.py
Labels: enhancement

#17 Support analysis mode
  setup.py
  src/fosslight_scanner/_help.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/common.py
  src/fosslight_scanner/fosslight_scanner.py
  tox.ini
Labels: enhancement

#19 Change the options when analyzing the source
  src/fosslight_scanner/fosslight_scanner.py
Labels: enhancement

#18 Move the binary analysis result file to output
  requirements.txt
  src/fosslight_scanner/fosslight_scanner.py
Labels: chore

#22 Modify to print output file name
  requirements.txt
  src/fosslight_scanner/fosslight_scanner.py
Labels: chore

#23 Update the README with additional Scanners
  README.md
Labels: documentation

#24 Add an inputable value to mode
  src/fosslight_scanner/_help.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/fosslight_scanner.py
Labels: chore
