Repository fosslight/fosslight_scanner, pull requests merged in 2022-03, with the labels that each got.

#26 Apply f-string format
  src/fosslight_scanner/common.py
  src/fosslight_scanner/fosslight_scanner.py
Labels: chore

#27 Extract the OSS name from the link
  src/fosslight_scanner/common.py
  src/fosslight_scanner/fosslight_scanner.py
  tox.ini
Labels: enhancement

#28 Print download location when analyzing as link
  src/fosslight_scanner/fosslight_scanner.py
Labels: enhancement

#29 Fix a bug where column names do not match when overwriting an excel
  src/fosslight_scanner/common.py
Labels: bug fix

#30 Fix errors that occur when downloading link
  src/fosslight_scanner/fosslight_scanner.py
Labels: bug fix
