Repository fosslight/fosslight_scanner, pull requests merged in 2022-07, with the labels that each got.

#37 Modify reuse input parameter
  requirements.txt
  src/fosslight_scanner/fosslight_scanner.py
Labels: bug fix

#38 Add compare mode
  .reuse/dep5
  requirements.txt
  setup.py
  src/fosslight_scanner/_help.py
  src/fosslight_scanner/_run_compare.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/fosslight_scanner.py
  src/fosslight_scanner/resources/bom_compare.html
  tests/after.yaml
  tests/before.yaml
Labels: enhancement, minor

#39 Print message when comparison rows are over 100.
  requirements.txt
  src/fosslight_scanner/_run_compare.py
  src/fosslight_scanner/fosslight_scanner.py
Labels: chore

#40 Fix scanner support format and not to create csv.
  src/fosslight_scanner/_run_compare.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/fosslight_scanner.py
  tox.ini
Labels: chore

#41 Replace 'y' option to 'p' option.
  src/fosslight_scanner/_help.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/fosslight_scanner.py
Labels: chore

#43 Change FL Reuse to FL Prechecker
  README.md
  requirements.txt
  src/fosslight_scanner/_help.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/fosslight_scanner.py
Labels: bug fix
