Repository fosslight/fosslight_scanner, pull requests merged in 2024-06, with the labels that each got.

#92 Supports for multiple modes
  requirements.txt
  src/fosslight_scanner/_get_input.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/fosslight_scanner.py
  tox.ini
Labels: enhancement

#94 Modify column name
  src/fosslight_scanner/common.py
Labels: chore

#96 When merging src to bin, remove src info instead of excluding
  src/fosslight_scanner/common.py
Labels: bug fix

#95 Supports for excluding paths from analysis
  README.md
  requirements.txt
  src/fosslight_scanner/_help.py
  src/fosslight_scanner/cli.py
  src/fosslight_scanner/common.py
  src/fosslight_scanner/fosslight_scanner.py
  tox.ini
Labels: enhancement
